[package]
name = "disk-dominator"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
chrono = "0.4"
tauri = { version = "1", features = [ "fs-all", "path-all", "os-all", "shell-open"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Local dependencies
logger_module = { path = "../core-modules/logger-module" }
auth_module = { path = "../core-modules/auth-module" }
i18n_module = { path = "../core-modules/i18n-module" }
ai_module = { path = "../core-modules/ai-module" }
storage_module = { path = "../core-modules/storage-module" }
update_module = { path = "../core-modules/update-module" }

# File system operations
walkdir = "2"
blake3 = "1.5"
rayon = "1.8"
notify = "6.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
