# DiskDominator Configuration Example
# Copy this file to config.toml and update with your settings

[app]
name = "DiskDominator"
version = "0.1.0"
debug = true

[storage]
data_dir = "./data"
cache_size_mb = 100
enable_compression = true

[ai]
# Provider options: "OpenAI", "Claude", "Ollama", "Mock"
provider = "Mock"

# API key for OpenAI or Claude (not needed for Ollama or Mock)
# api_key = "your-api-key-here"

# Model selection (optional, defaults are used if not specified)
# For OpenAI: "gpt-3.5-turbo", "gpt-4"
# For Claude: "claude-3-sonnet-20240229", "claude-3-opus-20240229"
# For Ollama: "llama2", "mistral", "codellama"
# model = "gpt-3.5-turbo"

# Temperature for AI responses (0.0 - 1.0)
temperature = 0.7

# Maximum retries for API calls
max_retries = 3

# Ollama base URL (only needed for Ollama provider)
# ollama_url = "http://localhost:11434"

[scanner]
# Maximum number of concurrent scan threads
max_threads = 4

# File size threshold for detailed analysis (in MB)
size_threshold_mb = 10

# Exclude patterns for scanning
exclude_patterns = [
    "node_modules",
    ".git",
    ".vscode",
    "target",
    "build",
    "dist",
    "__pycache__"
]

[ui]
# Theme: "light", "dark", "system"
theme = "system"

# Language code
language = "en-US"

# Show advanced features
advanced_mode = false

[performance]
# Maximum memory usage in MB
max_memory_mb = 500

# Enable file caching
enable_cache = true

# Cache expiry in hours
cache_expiry_hours = 24